In [6]:
!pip install datascience
!pip install -U scikit-learn
import pandas as pd
from datascience import *
import numpy as np
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.externals import joblib

Requirement already up-to-date: scikit-learn in /Users/edwardliu/Downloads/anaconda3/lib/python3.7/site-packages (0.21.3)


In [7]:
pwd

'/Users/edwardliu/Documents/dss-2019'

In [8]:
df = pd.read_csv('/Users/edwardliu/Documents/dss-2019/Data Frames/With Counts.csv')
tbl = Table.from_df(df).drop('article_link').drop(0)
tbl.show(3)

In [29]:
tbl_attributes = tbl.select(np.arange(2,7)).drop('Unique Useless Words').to_df().rename_axis('Attributes').values
x = tbl_attributes
y = tbl.column('is_sarcastic')

In [30]:
x_train, x_test, y_train, y_test = train_test_split(x,y)
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [35]:
mlp_relu = MLPClassifier(hidden_layer_sizes=(4,4,4),activation='relu',solver='lbfgs', max_iter=10000)
mlp_relu.fit(x_train,y_train)
predictions_relu = mlp_relu.predict(x_test)
print(confusion_matrix(y_test,predictions_relu))
print(classification_report(y_test,predictions_relu))

[[3701   70]
 [ 598 2786]]
              precision    recall  f1-score   support

           0       0.86      0.98      0.92      3771
           1       0.98      0.82      0.89      3384

    accuracy                           0.91      7155
   macro avg       0.92      0.90      0.91      7155
weighted avg       0.92      0.91      0.91      7155



In [36]:
mlp_logistic = MLPClassifier(hidden_layer_sizes=(4,4,4),activation='logistic',solver='lbfgs', max_iter=10000)
mlp_logistic.fit(x_train,y_train)
predictions_logistic = mlp_logistic.predict(x_test)
print(confusion_matrix(y_test,predictions_logistic))
print(classification_report(y_test,predictions_logistic))

[[3690   81]
 [ 564 2820]]
              precision    recall  f1-score   support

           0       0.87      0.98      0.92      3771
           1       0.97      0.83      0.90      3384

    accuracy                           0.91      7155
   macro avg       0.92      0.91      0.91      7155
weighted avg       0.92      0.91      0.91      7155



In [37]:
mlp_tanh = MLPClassifier(hidden_layer_sizes=(4,4,4),activation='tanh',solver='lbfgs', max_iter=10000)
mlp_tanh.fit(x_train,y_train)
predictions_tanh = mlp_tanh.predict(x_test)
print(confusion_matrix(y_test,predictions_tanh))
print(classification_report(y_test,predictions_tanh))

[[3676   95]
 [ 549 2835]]
              precision    recall  f1-score   support

           0       0.87      0.97      0.92      3771
           1       0.97      0.84      0.90      3384

    accuracy                           0.91      7155
   macro avg       0.92      0.91      0.91      7155
weighted avg       0.92      0.91      0.91      7155



In [38]:
mlp_identity = MLPClassifier(hidden_layer_sizes=(4,4,4),activation='identity',solver='lbfgs', max_iter=10000)
mlp_identity.fit(x_train,y_train)
predictions_identity = mlp_identity.predict(x_test)
print(confusion_matrix(y_test,predictions_identity))
print(classification_report(y_test,predictions_identity))

[[3639  132]
 [ 573 2811]]
              precision    recall  f1-score   support

           0       0.86      0.96      0.91      3771
           1       0.96      0.83      0.89      3384

    accuracy                           0.90      7155
   macro avg       0.91      0.90      0.90      7155
weighted avg       0.91      0.90      0.90      7155

